import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-zinc-900 text-white`}
      >
        <header className="flex justify-between items-center p-4 border-b border-zinc-700">
          <div className="flex items-center gap-2">
            <img src="/pahlavi-image.png" alt="Logo" className="w-6 h-6" />
            <h1 className="text-xl font-bold">Pahlavi Persian Press</h1>
          </div>
          <nav className="flex gap-6 text-sm text-zinc-300">
            <a href="/about">About</a>
            <a href="/help">Help</a>
            <a href="/publications">Publication Titles</a>
            <a href="/contact">Contact</a>
          </nav>
        </header>
        <main className="p-4">{children}</main>
      </body>
    </html>
  );
}
